# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_WEBAPP_NAME: ExtractQnA20230912211600
  AZURE_WEBAPP_PACKAGE_PATH: .\publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: DefaultResourceGroup-WUS
  AZURE_APIM_SERVICENAME: ExtractQnAapi2
  AZURE_APIM_API_ID: ExtractQnA
  AZURE_APIM_APPSERVICEURL: https://extractqna20230912211600.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  API_IMPORT_SPECIFICATION_PATH: .\publish\swagger.json
  API_IMPORT_DLL: .\Backend\ExtractQnA\bin\Release\net7.0\ExtractQnA.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: ./Backend/ExtractQnA

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
